Feature/products
bionanek/glasswitch-orders-web pull request #49
Opened 2019-05-08 16:27 UTC by elvixpix

2019-05-19 19:39 UTC, bionanek requested changes

2019-05-19 19:39 UTC, bionanek commented on src/components/products/components/modalCreate/ModalCreateProduct.js
> +		if (id === 'productPrice') {
can you use switch...case instead of if...else here

2019-05-19 19:39 UTC, bionanek commented on src/components/products/components/modalCreate/ModalCreateProduct.js
> +		if (form.checkValidity() === false) {
to reduce code nesting you can do 
```
if (form.checkValidity() === false) {
    event.stopPropagation()
    return;
}

setIsValidated(true)
const productData = buildProductData(product)
await ProductsApiService.postProduct(productData)

props.onModalClose()
props.onRefreshList()
setIsValidated(false)
```

2019-05-19 19:39 UTC, bionanek commented on src/components/products/components/modalCreate/ModalCreateProduct.js
> +		if (form.checkValidity() === false) {
and actually this part 
```
setIsValidated(true)
const productData = buildProductData(product)
await ProductsApiService.postProduct(productData)

props.onModalClose()
props.onRefreshList()
setIsValidated(false)
```
you could move out to a separate method

2019-05-19 19:39 UTC, bionanek commented on src/components/products/crud/ProductEdit.js
> +		if (id === 'productPrice') {
switch case

2019-05-19 19:39 UTC, bionanek commented on src/components/products/crud/ProductEdit.js
> +			event.stopPropagation()
if nesting

2019-05-21 19:11 UTC, bionanek requested changes

2019-05-21 19:11 UTC, bionanek commented on src/components/products/components/tile/ProductTileElement.js
> +	const pushDetailsPage = () => {
rename to openDetailsPage or goToDetailsPage

2019-05-21 19:11 UTC, bionanek commented on src/components/products/components/tile/ProductTileElement.js
> +	const pushEditPage = () => {
ditto

2019-05-21 19:11 UTC, bionanek commented on src/components/products/components/tile/ProductTileElement.js
> +	const openDeleteModal = () => {
there's no need for this method as it is used only in onDeleteButtonClick and it's just one line of code. So please move setIsDeleteModalOpen to onDeleteButtonClick

2019-05-21 19:11 UTC, bionanek commented on src/components/products/components/tile/ProductTileElement.js
> +		} else {
remove Else, instead do 
```
if (props.element.deleteHandler) {
 			props.element.deleteHandler(props.element.id)
      return;
}
props.defaultOnDeleteClick(props.element, props.index)
```

2019-05-21 19:11 UTC, bionanek commented on src/components/products/components/tile/ProductTileElement.scss
> +.product-tile {
maybe u can aply this style inline in JSX?

2019-05-21 19:11 UTC, bionanek commented on src/components/products/list/ProductsList.js
> +							<Button variant="secondary" onClick={this.renderListView}>
can u add a little spacing between these 2 buttons

2019-05-21 19:11 UTC, bionanek commented on src/components/products/list/ProductsList.js
> +					<Row className="product-tile">
you either have to remove Row from here or from ProductTile because what happens now is <row><row><youTileStuff /></row></row>

2019-05-21 19:15 UTC, elvixpix commented on src/components/products/components/tile/ProductTileElement.js
> +	const pushDetailsPage = () => {
done

2019-05-21 19:15 UTC, elvixpix commented on src/components/products/components/tile/ProductTileElement.js
> +	const pushEditPage = () => {
done

2019-05-21 19:16 UTC, elvixpix commented on src/components/products/components/tile/ProductTileElement.js
> +	const openDeleteModal = () => {
done

2019-05-21 19:17 UTC, elvixpix commented on src/components/products/components/tile/ProductTileElement.js
> +		} else {
done

2019-05-22 18:13 UTC, bionanek submitted a review, later dismissed

2019-05-23 09:03 UTC, bionanek approved these changes

2019-05-23 09:04 UTC, merged